accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth.views import logout_then_login


urlpatterns = [
    path('send_login_email/', views.send_login_email, name='send_login_email'),
    path('login/', views.login, name='login'),
    path('logout/', logout_then_login, name='logout')
]

lists/urls.py
from django.contrib import admin
from django.urls import path, include
from lists import views

urlpatterns = [
    path('<int:list_id>/', views.view_list, name='view_list'),
    path('new', views.new_list, name='new_list'),
    path('users/<str:email>/', views.my_lists, name="my_lists"),
]

superlists/urls.py
#from django.contrib import admin
from django.urls import path, include
from lists import views as list_views
from lists import urls as list_urls
from accounts import urls as accounts_urls


urlpatterns = [
   # path('admin/', admin.site.urls),
    path('', list_views.home_page, name="home"),
    path('lists/', include(list_urls)),
    path('accounts/', include(accounts_urls)),
]

accounts/models.py
import uuid
from django.db import models


class User(models.Model):
    '''Пользователь'''
    email = models.EmailField(primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    """маркер"""

    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class List(models.Model):
    '''Список'''
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse("view_list", args=[self.id])
    
    @property
    def name(self):
        return self.item_set.first().text
    
    @staticmethod
    def create_new(first_item_text, owner=None):
        '''создать новый'''
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_
    
class Item(models.Model):
    """элемент списка"""
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Item, List


EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):
    '''форма для элемента списка'''

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg',
            })
        }

        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }
    

class NewListForm(ItemForm):
    '''форма для нового списка'''
    
    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])


class ExistingListItemForm(ItemForm):
    '''форма для элемента существующего списка'''
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        """проверка уникальности"""
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.contrib import messages, auth
from django.urls import reverse

from accounts.models import Token


def send_login_email(request):
    '''отправить сообщение для входа в систему'''
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('login') + '?token=' + str(token.uid)
    )
    message_body = f'Use this link to log in:\n\n{url}'
    send_mail(
        'Your login link for Superlists',
        message_body,
        'klimrus61@yandex.ru',
        [email],
    )
    messages.success(
        request,
        "Check your mail, we sent the link for you, \
        which you can use for login on site."
    )
    return redirect('/')

def login(request):
    '''Авторизовать пользователя'''
    user = auth.authenticate(request, uid=request.GET.get('token'))
    if user:
        auth.login(request, user)
    return redirect('/')

lists/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from lists.forms import ItemForm, ExistingListItemForm, NewListForm
from lists.models import Item, List


User = get_user_model()


def home_page(request):
    """Домашняя страница"""
    return render(request, 'home.html', {'form': ItemForm()})

def view_list(request, list_id):
    '''представление списка'''
    list_ = List.objects.get(id=list_id)

    if request.method == "POST":
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    else:
        form = ExistingListItemForm(for_list=list_)
    return render(request, 'list.html', {
        'list': list_, "form": form,
    })

def new_list(request):
    '''новый список'''
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})

def my_lists(request, email):
    '''Списки пользователя'''
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

lists/templates/base.html
<html>

<head>
  <title>To-Do list</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link href="/static/base.css" rel="stylesheet">
</head>

<body>
  <div class='container'>

    <nav class='navbar navbar-default' role="navigation">
      <div class="container-fluid">
        <a class="navbar-brand" href='/'>Superlists</a>
        {% if user.email %}
          <ul class="nav navbar-nav navbar-left">
            <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="navbar-text">Logged is as {{ user.email }}</li>
            <li><a href="{% url 'logout' %}">Log out</a></li>
          </ul>
        {% else %}
          <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
            <span>Enter email to log in:</span>
            <input class="form-control" name="email" type="text" />
            {% csrf_token %}
          </form>
        {% endif %}
      </div>
    </nav>
    
    {% if messages %}
      <div class="row">
        <div class="col-md-8">
          {% for message in messages %}
            {% if message.level_tag == 'success' %}
              <div class="alert alert-success">{{ message }}</div>
            {% else %}
              <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    {% endif %}

    <div class='row justify-content-md-center'>
      <div class="col-md-6 col-md-offset-3 jumbotron">
        <div class="text-center">
          <h1>{% block header_text %}{% endblock %}</h1>
          {% block list_form %}
            <form method='POST' action="{% block form_action %}{% endblock %}">
              {{ form.text }}
              {% csrf_token %}
              {% if form.errors %}
              <div class='form-group has-error'>
                <span class="help-block">{{ form.text.errors }}</span>
              </div>
              {% endif %}
            </form>
          {% endblock %}
        </div>
      </div>
    </div>
    <div class="row justify-content-md-center">
      <div class="col-md-6 col-md-offset-3">
        {% block table %}
        {% endblock %}
      </div>
    </div>
    <div class="row justify-content-md-center">
      <div class="col-md-6 col-md-offset-3">
        {% block extra_content %}
        {% endblock extra_content %}
      </div>
    </div>
  </div>
<script src="/static/jquery-3.6.2.js"></script>
<script src="/static/list.js"></script>

<script>
$(document).ready(function () {
  window.Superlists.initialize();
});
  
</script>
</body>

</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a To-Do list{% endblock  %}

{% block form_action %}{% url 'new_list' %}{% endblock form_action %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock header_text %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock form_action %}

{% block table %}
    <table id='id_list_table' class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{forloop.counter}}: {{ item.text }} </td></tr>
        {% endfor %}
    </table>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text%}My lists{% endblock %}

{% block list_form %}{% endblock list_form %}

{% block extra_content %}
    <h2>{{ owner.email }}
    <ul>
        {% for list in owner.list_set.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock extra_content %}